### ISSUE TITLE
Expose the RNG as a hyper-parameter

### ISSUE THREAD

**Issue by ablaom** [PyDataBlog/ParallelKMeans.jl#66]
For easier reproducibility. 

Your algorithm is parallelized, so some thought must be given to that. I'm guessing random number generation only happening on the master process? Otherwise you might have to expose multiple RNG's (which MLJ does in `learning_curve`).

In MLJ the "standard" way to expose an RNG is to make it a hyperparameter `rng=Random.GLOBAL_RNG` which user can set to any `AbstractRNG` or to an integer (meaning "use `MersenneTwister(rng)` as your generator.")

**Comment by PyDataBlog** [comment]
@ablaom any example on how other models expose this hyperparameter?

**Comment by ablaom** [comment]
Actually, not many do 😞 . You can look at the EnsembleModel wrapper https://github.com/alan-turing-institute/MLJ.jl/blob/d3a5937e78719a14205dc92ad2e1ee501fb8dc6e/src/ensembles.jl#L188

**Comment by PyDataBlog** [comment]
> Actually, not many do  . You can look at the EnsembleModel wrapper https://github.com/alan-turing-institute/MLJ.jl/blob/d3a5937e78719a14205dc92ad2e1ee501fb8dc6e/src/ensembles.jl#L188

I will look into it and ask for your input (if need be).

**Comment by Arkoniak** [comment]
For clarification.

Currently, all of our algorithms are generally deterministic, there are following exceptions.

1. Seeding `kmeans++` algorithm (common for all algorithms), it is multithreaded, but `RNG` only on master thread: https://github.com/PyDataBlog/ParallelKMeans.jl/blob/master/src/seeding.jl#L85 (also L98, L117)

2. Yinyang uses internally `kmeans` for initialization, so `RNG` should be pushed there as well: https://github.com/PyDataBlog/ParallelKMeans.jl/blob/master/src/yinyang.jl#L161

3. Future implementation of MiniBatchKMeans #55 , should be written with `RNG` support

**Comment by Arkoniak** [comment]
Related to #80
