### ISSUE TITLE
Smart init needs to be thoroughly vetted and tested. Currently buggy and unstable

### ISSUE THREAD

**Issue by PyDataBlog** [PyDataBlog/ParallelKMeans.jl#7]
Convergence seems to be unstable at different tolerance levels plus sum of squares values jump around a lot at different K values. 

```julia
using Plots
using Clustering
using ParallelKMeans

X = rand(10000, 30);

@time a = [Clustering.kmeans(X', i).totalcost for i = 2:10];
@time b = [ParallelKMeans.kmeans(X, i, tol=1e-6, verbose=false)[end] for i = 2:10];

plot(a)
plot!(b)
```

**Comment by Arkoniak** [comment]
I think we should seek inspiration here: https://github.com/JuliaStats/Clustering.jl/blob/master/src/seeding.jl#L143

**Comment by PyDataBlog** [comment]
Extensively testing #13 to verify if it fixes this issue finally.

**Comment by PyDataBlog** [comment]
#16 should give a more stable init. Further testing needed to verify
