### ISSUE TITLE
Benchmark figure

### ISSUE THREAD

**Issue by azev77** [PyDataBlog/ParallelKMeans.jl#79]
Hi and thanks for this package. 
In the benchmark figure in the readme, can you make the PK implementations easier to view & disentangle from the others? 
For example, may make them dashed, or thicker, or have a different marker...
Or make all the PK the same color except w/ different markers...

**Comment by PyDataBlog** [comment]
@azev77 that's a good point. The next patch release will make PK implementations easier to view.

**Comment by azev77** [comment]
@PyDataBlog 
Any updates?

**Comment by PyDataBlog** [comment]
> @PyDataBlog 
> 
> Any updates?

I'll work on this from this weekend. Had to deal with some personal stuff :)

**Comment by azev77** [comment]
@PyDataBlog any news :)

**Comment by PyDataBlog** [comment]
> @PyDataBlog any news :)

@azev77

A minor update is planned this week. You will get an update, fingers crossed.

**Comment by PyDataBlog** [comment]
@azev77 once #101 is sorted, the benchmarks will be updated and released :)

**Comment by PyDataBlog** [comment]
@azev77 almost there. #101 merged. #78  is in progress now. Any update to this plot request since you last made it? 😃

**Comment by azev77** [comment]
Not really. Would be nice to make it easier to quickly visualize which benchmarks are for your package "PK" & which are others. 

Example: Make all curves for PK w/ dashed lines

**Comment by PyDataBlog** [comment]
@azev77 #112 has the figure you requested. Closing now for release. Re-open if you want any further adjustments.
