### ISSUE TITLE
Extend [compat] MLJModelInterface = "^0.2,^0.3"

### ISSUE THREAD

**Issue by ablaom** [PyDataBlog/ParallelKMeans.jl#89]
Supervised classifiers in MLJ now require a lower bound of 0.3 to buy into a performance boost. So you may find users complaining that adding ParallelKMeans to their MLJ environment downgrades performance of other models unless you update. 

There should be nothing breaking about this update. 

Questions welcome.

**Comment by Arkoniak** [comment]
Thank you for noticing, we've merged `Compat` PR, but forget to bump version.
